browser_exe_path: ""
user_data_dir: "D:\\Code\\GithubProject\\boss_mcp\\data\\session"
qr_output_path: "D:\\Code\\GithubProject\\boss_mcp\\data\\session\\qr_code.png"
llm_provider:
  openai:
    base_url: https://ai-gateway.pgthinker.me
    api_key: 
    model: deepseek/deepseek-v4-flash

  # ... 其它AI服务商